import type { Metadata } from "next";
import "./globals.css";
import { fonts } from "./fonts";

export const metadata: Metadata = {
  title: "NextJs Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fonts.raleway} antialiased`}
        suppressHydrationWarning={true}
      >
        {children}
      </body>
    </html>
  );
}
